version: '3.4'

services:
  authdatabase:
    image: postgres:latest

  messengerdatabase:
    image: postgres:latest

  redis:
    image: redis:alpine

  redisinsight:
    image: redislabs/redisinsight:latest

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.2

  kibana:
    image: docker.elastic.co/kibana/kibana:7.9.2

  portainer:
    image: portainer/portainer-ce:latest

volumes:
  postgres_data_auth_database:
  postgres_data_messenger_database:
  elasticsearch_data:
  portainer_data:
  redis_insight_data:
